title: "Oscar Ahumada - Portfolio"
description: "Professional website built with Jekyll and GitHub Pages"
baseurl: ""
url: "https://oscarahumadag.github.io"

# Usa el tema remoto en lugar del local
remote_theme: jekyll/minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown

# Lenguaje del sitio
lang: "en"

# Sass settings
sass:
  style: compressed
